name: Deploy_Envs
run-name: 'Environment:${{ inputs.configuration }} | WhatIf:${{ inputs.what-if }}'

on:
  workflow_dispatch:
    inputs:
      configuration:
        description: Target environment
        required: true
        type: choice
        options:
          - rg-poc-dev-eastus
          - rg-poc-prod-eastus

      what-if:
        description: Execute a what-if instead of the deployment
        required: true
        type: boolean
        default: true

      operation:
        description: Operation to perform
        required: true
        type: choice
        default: deploy-all
        options:
          - deploy-all
          - deploy-virtual-network
          - deploy-storage-account

permissions:
  id-token: write
  contents: read

jobs:
  config:
    uses: ./.github/workflows/workflow-map-configuration.yaml
    with:
      configuration: ${{ inputs.configuration }}

  deploy-virtual-network:
    needs: config
    if: ${{ inputs.operation == 'deploy-all' || inputs.operation == 'deploy-virtual-network' }}
    runs-on: ubuntu-latest
    environment: ${{ needs.config.outputs.resource_group }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: VNet What-If
        if: ${{ inputs.what-if == true }}
        run: |
          az deployment group what-if \
            --resource-group '${{ needs.config.outputs.resource_group }}' \
            --template-file './environments/dev/eastus/vnet/main.bicep' \
            --parameters './environments/dev/eastus/vnet/main.${{ inputs.configuration }}.bicepparam'

      - name: Deploy VNet
        if: ${{ inputs.what-if == false }}
        run: |
          az deployment group create \
            --resource-group '${{ needs.config.outputs.resource_group }}' \
            --name "vnet-${{ inputs.configuration }}-${{ github.run_number }}" \
            --template-file './environments/dev/eastus/vnet/main.bicep' \
            --parameters './environments/dev/eastus/vnet/main.${{ inputs.configuration }}.bicepparam'

  deploy-storage-account:
    needs: config
    if: ${{ inputs.operation == 'deploy-all' || inputs.operation == 'deploy-storage-account' }}
    runs-on: ubuntu-latest
    environment: ${{ needs.config.outputs.resource_group }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Storage What-If
        if: ${{ inputs.what-if == true }}
        run: |
          az deployment group what-if \
            --resource-group '${{ needs.config.outputs.resource_group }}' \
            --template-file './environments/dev/eastus/stg/main.bicep' \
            --parameters './environments/dev/eastus/stg/main.${{ inputs.configuration }}.bicepparam'

      - name: Deploy Storage
        if: ${{ inputs.what-if == false }}
        run: |
          az deployment group create \
            --resource-group '${{ needs.config.outputs.resource_group }}' \
            --name "stg-${{ inputs.configuration }}-${{ github.run_number }}" \
            --template-file './environments/dev/eastus/stg/main.bicep' \
            --parameters './environments/dev/eastus/stg/main.${{ inputs.configuration }}.bicepparam'