name: Map Configuration to Environment
on:
  workflow_call:
    inputs:
      configuration:
        type: string
        required: true
    outputs:
      resource_group:
        value: ${{ jobs.map.outputs.resource_group }}
      region:
        value: ${{ jobs.map.outputs.region }}
      deployment_stack_name:
        value: ${{ jobs.map.outputs.deployment_stack_name }}
      action_on_unmanage:
        value: ${{ jobs.map.outputs.action_on_unmanage }}
      landing_zone_path:
        value: ${{ jobs.map.outputs.landing_zone_path }}

permissions:
  contents: read

jobs:
  map:
    runs-on: ubuntu-latest
    env:
      mapping-file: .github/workflows/configuration-environment-map.jsonc
    outputs:
      resource_group: ${{ steps.map.outputs.resource_group }}
      region: ${{ steps.map.outputs.region }}
      deployment_stack_name: ${{ steps.map.outputs.deployment_stack_name }}
      action_on_unmanage: ${{ steps.map.outputs.action_on_unmanage }}
      landing_zone_path: ${{ steps.map.outputs.landing_zone_path }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Determine Mapping
        id: map
        shell: pwsh
        run: |
          $mapping = Get-Content -Raw -Path "${{ env.mapping-file }}" | ConvertFrom-Json -AsHashtable
          $result = $mapping["${{ inputs.configuration }}"]
          if ($null -eq $result) {
            Write-Output "::error title=Unexpected Configuration::'${{ inputs.configuration }}' not found in mapping file."
            exit 1
          }
          $r = [PSCustomObject]$result
          echo "resource_group=$($r.RESOURCE_GROUP)"           | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "region=$($r.REGION)"                           | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "deployment_stack_name=$($r.DEPLOYMENT_STACK_NAME)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "action_on_unmanage=$($r.ACTION_ON_UNMANAGE)"   | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          echo "landing_zone_path=$($r.LANDING_ZONE_PATH)"     | Out-File -FilePath $env:GITHUB_OUTPUT -Append